pro:
  main:
    database: peak
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    dbargs: charset=utf8&parseTime=True&loc=Local
    pool: 5
  backup:
    database: peak_backup
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    dbargs: charset=utf8&parseTime=True&loc=Local
    pool: 5
dev:
  main:
    database: peak_dev
    username: root
    password: root12345678
    host: 127.0.0.1
    port: 3306
    dbargs: charset=utf8&parseTime=True&loc=Local
    pool: 5
  backup:
    database: peak_dev_backup
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    dbargs: charset=utf8&parseTime=True&loc=Local
    pool: 5